### PR TITLE
[WIP] install bash and procps in docker version for nextflow

### PR DESCRIPTION
**Pull request by rmillikin**
this PR installs bash and procps in the Linux docker image. bash is required to run metamorpheus in a nextflow pipeline, and procps lets nextflow monitor computational resources used by the image.

### CODE REVIEW

**Comment by rmillikin** [comment]
getting a weird failure message from docker. will investigate

**Review by zrolfs — APPROVED** [review]
No idea what's going on here, but I'll approve it for bureaucracy's sake

**Comment by rmillikin** [comment]
seems to be a bug with Docker version 2.2.0.5, which is the version appveyor is running. https://github.com/microsoft/hcsshim/issues/813

**Review by rmmiller22 — APPROVED** [review]

**Review by trishorts — APPROVED** [review]
same as zach. seems innocuous enough and unlikely to break to MM. I can wait til the release happens and try to run the docker I guess.

Just asking, is their a way to download the docker from Appveyor and test it just like we download the installer?

**Pull request merged**
