### PR TITLE
Add conda badges

### PR DESCRIPTION
**Pull request by acesnik**

### CODE REVIEW

**Comment by acesnik** [comment]
Got MM into conda-forge! Available on Windows, macOS, and Linux: https://anaconda.org/conda-forge/metamorpheus

There's an issue with conda-forge's `dotnet` that I'm trying to resolve before we merge this.

**Review by zrolfs — APPROVED** [review]

**Review by trishorts — APPROVED** [review]

**Comment by acesnik** [comment]
The issue with conda-forge's `dotnet` that I mentioned before is resolved now, so this should be ready to go.

**Comment by rmillikin** [comment]
how do releases work w/ conda? the reason I ask is because the current MM release (0.0.317) is on .NET 3.1 and not .NET 5. When @rmmiller22 makes a new release, it will be on .NET 5. should this PR get merged after the next release? seems odd to merge it before if there isn't an actual .NET 5 release for people to use. or does MM work with .NET 3.1 on conda?

**Review by rmillikin — APPROVED** [review]

**Comment by acesnik** [comment]
Yes, MM 0.0.317 works with dotnet 3.1 on conda, so this is okay to merge before the next release.

I've been manually updating the releases on `conda` or accepting automatic PRs from a conda-forge feedstock tools. It'll be updated to target .NET 5.0 after the next release.

**Pull request merged**
