### PR TITLE
Add ion series info

### PR DESCRIPTION
**Pull request by zrolfs**

### CODE REVIEW

**Comment by rmillikin** [comment]
for matched ion series output I get this:
[[b2+1, b9+1, b10+1, b11+1, b12+1];[y1+1, y2+1, y3+1, y4+1, y5+1, y6+1, y7+1, y8+1, y9+1, y10+1, y11+1, y12+1];]

I assume it is supposed to be b3, b10, b11, etc ?

**Comment by zrolfs** [comment]
The b ions are working as intended from line 208 in MetaMorpheusEngine.cs

           //matchedIonSeries assumes 1-n, but bnob1 has no b1, so we need to ++ each series number
            if (productType == ProductType.BnoB1ions)
            {
                for (int i = 0; i < matchedIonSeries.Count; i++)
                {
                    matchedIonSeries[i]++;
                }
            }

**Comment by rmillikin** [comment]
capture

I think you are trying to add one to the ion series number which is fine but in the output it is not format like you intend (I think?)

**Comment by zrolfs** [comment]
It looks as intended, I'm not sure what you mean.
The +1 is from the charge. This is a standard notation.

**Comment by zrolfs** [comment]
The charge addresses 4. from #1233

**Comment by rmillikin** [comment]
Ah I see, I understand. looks good

**Pull request merged**
