### PR TITLE
XL-search and Glycan search

### PR DESCRIPTION
**Pull request by lonelu**
1. update crosslink scoring method. 
2. enable glycan search.
3. Fix bug reported by users.

### CODE REVIEW

**Comment by rmillikin** [comment]
This really needs to be broken up into two pull requests.
1. Cross-link stuff
2. Glycan search

I'm happy to merge any changes/fixes to cross-link.

The glycan search appears to affect a lot of core code. Also there is a huge 3 million line glycan database from another group attached? I think this search is going to require some discussion. Also, for the sake of Shortreed's sanity, I think we should hold off on merging large changes to the code until the new mzLib changes are merged in. I think it will affect how glycans are searched for too.

**Comment by lonelu** [comment]
I don't think it is easy to break into two pull request. I change a lot of basic stuff. I'll delete this pull request. And fix the bugs reported first.

**Comment by lonelu** [comment]
I don't know how to delete this pull request. Please help delete it if you want to.

**Comment by rmillikin** [comment]
If you want help splitting this I can talk to you about it. It will involve making another fork and copying some changes over to that one, then making a pull request here from that fork. I'll talk to you about it tmw

**Comment by lonelu** [comment]
OK.

**Comment by acesnik** [comment]
I had to do a lot of this breaking up of pull requests in July. It's a hassle, but helps clarify the pull request by making sure all the changes are related to a certain goal. 

I'd recommend:
1) Make a separate clone fresh from the master branch on your computer
2) Make a branch (`git checkout -b CrossLinkStuff`) in the new clone
3) Transfer the minimal set of changes needed for the new feature
4) Push the new branch to smith-chem-wisc directly (`git push origin CrossLinkStuff`, where origin is smith-chem-wisc on the new clone)
5) Make a pull request from smith-chem-wisc/CrossLinkStuff to smith-chem-wisc/master. This also allows others (e.g. Rob or me) to push small commits to fix typos or the like.

**Pull request closed without merging**
