### PR TITLE
Write spectrum library from PsmTsv in MetaDraw

### PR DESCRIPTION
**Pull request by trishorts**
I'd like to be able to create library spectra in MetaDraw. For this to happen, we need to be able to use the info from PsmTsv to generate the spectrum. This PR adds a new method to PsmFromTsv called ToLibrarySpectrum() that produces the library spectrum object. Once you have a library spectrum object, you simply need to call the .ToString() method to get the .msp format.

I copied the pdf/png export code in MetaDraw and added a button in the gui that lets the user export any number of selected PSMs for immediate export into a spectrum library.

The output was tested both in metadraw and in search. The written libraries load into metadraw and produce spectral angles in search.

I did need to update psmtsv read to correctly accomodate child scans (MS3) for both crosslink and glyco. There was previously an error reading the scan intesnities.

### CODE REVIEW

**Comment by Alexander-Sol** [comment]
I feel like ToLibrarySpectrum should spit out a LibrarySpectrum object. Then you could call to string or whatever on that. If we ever change how spectral libraries are written, I don't want to have to edit multiple different ToLibrarySpectrum methods

**Review by Alexander-Sol — CHANGES_REQUESTED** [review]
I feel like ToLibrarySpectrum should spit out a LibrarySpectrum object. Then you could call to string or whatever on that. If we ever change how spectral libraries are written, I don't want to have to edit multiple different ToLibrarySpectrum methods

**Comment by trishorts** [comment]
> I feel like ToLibrarySpectrum should spit out a LibrarySpectrum object. Then you could call to string or whatever on that. If we ever change how spectral libraries are written, I don't want to have to edit multiple different ToLibrarySpectrum methods

that makes sense. It is done now.

**Review by nbollis — APPROVED** [review]

**Review by Alexander-Sol — APPROVED** [review]

**Comment by trishorts** [comment]
i broke this writing glyco spectrum library

**Review by nbollis — APPROVED** [review]

**Pull request merged**
