### PR TITLE
Adding scrollable sequence, ability to save settings, and select the spectrum description line by line to MetaDraw

### PR DESCRIPTION
**Pull request by nbollis**
Added a scrollable sequence to MetaDraw and prevented long sequences from running off of the screen
Broke up some of the visual components into their own classes

### CODE REVIEW

**Comment by trishorts** [comment]
whats w/ the grey box on top right?
image

**Comment by trishorts** [comment]
either reset button only resets the adjacent line or go to one reset button:
image

**Comment by trishorts** [comment]
reset should clear annotation 
image

**Comment by trishorts** [comment]
mouse over to view doesn't work 
image

**Comment by trishorts** [comment]
click shifts top but not lower sequence 
image

**Comment by trishorts** [comment]
numbering is confusing. left G is AA#2 and right S is AA#30: Is it hard to put number below AA, then the numbering would be more clear. it's hard to understand when you add the numbers as if they were AAs. 
image

**Review by trishorts — APPROVED** [review]
nice PR nicd

**Review by Yuling1996 — APPROVED** [review]

**Review by avcarr2 — APPROVED** [review]
Good job on the pr. Can you add a paragraph or links somewhere on MVC architecture so anybody working in MetaDraw in the future can reference them?

**Review by avcarr2 — APPROVED** [review]

**Review by rmmiller22 — APPROVED** [review]

**Pull request merged**
