### PR TITLE
call retention time calibration function in FlashLFQ

### PR DESCRIPTION
**Pull request by rmillikin**

### CODE REVIEW

**Comment by stefanks** [comment]
Would you please add the parameter to the task5 in the examples folder? And to any existing unit test? Thanks!

**Comment by rmillikin** [comment]
didn't even know we had an examples file, will do!

**Comment by stefanks** [comment]
These serve as examples, but also are run on appveyor and Jenkins, separately from unit tests

**Comment by rmillikin** [comment]
rewrote the quant unit test to use the sliced raw file 8)

**Pull request merged**
