### PR TITLE
Function to violate FDR not quite as badly when not reporting ambiguity.

### PR DESCRIPTION
**Pull request by zrolfs**
Issue #656

### CODE REVIEW

**Comment by zrolfs** [comment]
New merge strategy makes it more difficult to discern which changes have been made IMO.

**Comment by stefanks** [comment]
I'll look at this pull request closely after lunch. 

The new merge strategy exists so that the commit history of the master branch is easy to parse and follow. Now it does does not include a huge number of commits that were a part of debugging/development efforts, and only includes clean commits. 

If you want to avoid having a huge old commit history in your pull requests, do not keep developing on a branch that has been previously merged into the master.

**Comment by stefanks** [comment]
Ah, actually it is a small pull request! I'm uneasy about it though. I would rather we overestimate the FDR than underestimate it!

Anyone else have a strong opinion about this?

**Comment by zrolfs** [comment]
It is a dramatic overestimation of FDR with the previous code and a marginally slight underestimation with these changes. Users who select ambiguity (the default) will continue to experience the overestimation, however they will be aware of them.

**Comment by zrolfs** [comment]
I disagree with codacy, unless you think it's valid.

**Comment by stefanks** [comment]
Good point!

**Pull request merged**
