### PR TITLE
Net eight

### PR DESCRIPTION
**Pull request by trishorts**
Update MM to .Net 8.0 with accompanying changes to nuget packages and wix.
Changes to all .csproj files
Added Nunit legacy to avoid annoying changes that accompany Nunit updates.

The following were updated:
MathNet.Numerics.MKL.Win" Version="3.0.0"
Microsoft.ML" Version="3.0.1"
Microsoft.ML.CpuMath" Version="3.0.1"
Microsoft.ML.FastTree" Version="3.0.1"
Newtonsoft.Json" Version="13.0.3"
SharpLearning.CrossValidation" Version="0.31.8"
SharpLearning.GradientBoost" Version="0.31.8"
SharpLearning.Metrics" Version="0.31.8"
System.CodeDom" Version="8.0.0"
System.Collections.Immutable" Version="8.0.0"
System.Drawing.Common" Version="8.0.7"
System.Memory" Version="4.5.5"
System.Runtime.CompilerServices.Unsafe" Version="6.0.0"
System.Threading.Tasks.Dataflow" Version="8.0.1"

### CODE REVIEW

**Comment by Alexander-Sol** [comment]
image
This error gets thrown at the very end of tasks

**Comment by trishorts** [comment]
> image This error gets thrown at the very end of tasks

You might have an empty net6.0 folder in gui/bin/debug that is acting as bait. happens when you switch between versions. maybe you could look and delete and retry? 
image

**Review by Alexander-Sol — COMMENTED** [review]
In PeptideSpectralMatchTest, line 36 should be changed to string 

`pairedTargetDecoyHash = null;` 

to be compatible with the current master of mzLib

**Review by nbollis — APPROVED** [review]

**Comment by elaboy** [comment]
can you target both net 6.0 and net 8.0?

**Review by elaboy — APPROVED** [review]

**Review by RayMSMS — APPROVED** [review]

**Pull request merged**
