### PR TITLE
Update to .NET 6.0

### PR DESCRIPTION
**Pull request by acesnik**
## Update to .NET 6.0
* Pending mzLib update to net6.0, https://github.com/smith-chem-wisc/mzLib/pull/615
* Includes changes to installer with new native libraries in net6.0 for linux and osx

## Issue arising with spectral library generation
There is one error arising in library generation. @Yuling1996, could this be due to how mzMLs are printed in dynamic loading with mzLib? I had to change how mzMLs are printed, and the whitespace at the beginning of lines may have changed.

image

### CODE REVIEW

**Comment by trishorts** [comment]
rachel and i worked on getting this to build in appveyor. complicated. wix on our local machines is bugged. looks like it needs vs update. i think we'll work more onit tomorrow.

**Comment by acesnik** [comment]
I merged in your changes to the tests and such here (nice work on that!). Upon closer inspection this afternoon, I realized you were missing my changes to the installer, which is building in this PR.

**Comment by trishorts** [comment]
cool. hope it builds. really want to get this done

**Comment by acesnik** [comment]
I merged @trishorts's PR, https://github.com/smith-chem-wisc/MetaMorpheus/pull/2136 into here, and it's building!

The installer changes and dockerfile changes were needed for AppVeyor to work.

**Review by trishorts — APPROVED** [review]

**Review by trishorts — COMMENTED** [review]
I think changes to the product.wxs are causing problems. if you install this version of mm it can't find fasttreenative. If I rename the folder from nativeWin to native it works

**Comment by trishorts** [comment]
appveyor builds but the installed version crashes

**Comment by acesnik** [comment]
When it builds, is the folder "native" or "nativeWin"?

**Comment by trishorts** [comment]
nativeWin

**Comment by acesnik** [comment]
Strange, so it's expecting a different name than it's building? Here's the line that names the folder in the installed directory. https://github.com/smith-chem-wisc/MetaMorpheus/blob/master/MetaMorpheusSetup/Product.wxs#L67

**Comment by acesnik** [comment]
I'd recommend changing that line to have native, rather than nativeWin, building the installer, and trying it out and seeing if it fixes your crash. (I ran a small test of the installed app back in March but didn't run into a crash.)

**Pull request merged**
