### PR TITLE
Set icon in add/remove programs

### PR DESCRIPTION
**Pull request by acesnik**

### CODE REVIEW

**Comment by acesnik** [comment]
This is ready to review.

**Comment by rmillikin** [comment]
@acesnik please pick another reviewer (aside from me), we're doing 2 reviewers + me now

**Comment by acesnik** [comment]
I can't assign reviewers. @trishorts Do you want to take a look at this? It adds the icon to the Add/Remove program menu.

image

**Comment by trishorts** [comment]
what  will you give me

**Comment by trishorts** [comment]
My attempt to get this to work has not been successful yet. I got ACs PR on my machine and installed from that build. But, no icon showed up in the Apps program. Still the old default. 

Stay tuned.

**Comment by acesnik** [comment]
Thanks for giving it a try, Michael. I've tried it in the following situations, and the installer with the added code gives me the icon in the add/remove programs page every time.

* With version 0.0.308 installed, it has the default icon, and when installing from "Debug" or "Release," it installs and the icon is visible in the add/remove programs page
* Without a version of MM installed previously, same result for both "Debug" and "Release"

image (17)

**Comment by trishorts** [comment]
image
voila!

**Pull request merged**
