### PR TITLE
MetaDraw Fragmentation Reanalysis

### PR DESCRIPTION
**Pull request by nbollis**
Enables the reanalysis of a fragmentation spectrum with additional fragment ion types. 

The plotting methods use the MatchedIons of the psm that gets passed in to determine what to plot. To enable this functionality, I had to temporarily replace the fragment ions in the psm with the new matched ions, then put the original ions back in once the plotting has finished. 

To use: have your normal MetaDraw Display
image

Select the additional ions you want to search for
image

His the search button. The persist check box will enable this research on all new PSMs you plot

image

### CODE REVIEW

**Comment by trishorts** [comment]
pretty cool. i only ever see yAmmoniaLoss. maybe we need unit tests for each of the ion types? sounds like lots of work...... I wonder if we paste a couple of example spectra into proteinprospector if it sees any other fragments.

**Comment by nbollis** [comment]
> pretty cool. i only ever see yAmmoniaLoss. maybe we need unit tests for each of the ion types? sounds like lots of work...... I wonder if we paste a couple of example spectra into proteinprospector if it sees any other fragments.
That is a good idea and maybe a good starter project. Our current tests only truly test b, y, and c ions

**Review by Alexander-Sol — APPROVED** [review]
I pulled it and it worked great

**Review by avcarr2 — APPROVED** [review]

**Comment by trishorts** [comment]
is the top supposed to look like this? 
image

**Comment by trishorts** [comment]
i think that export spectrum library should maybe contain the newly annotated fragments. 
image

**Comment by nbollis** [comment]
> is the top supposed to look like this? image

This has been fixed

**Review by trishorts — APPROVED** [review]

**Pull request merged**
