### PR TITLE
Optionally specify a data directory for command-line

### PR DESCRIPTION
**Pull request by rmillikin**
optionally specify a data directory, change a couple data dir things to prevent crashes on readonly filesystems

#1818

### CODE REVIEW

**Comment by rsdmse** [comment]
@rmillikin Thanks a lot for fixing this issue. We have a group of users on our HPC cluster waiting to use this software. If the PR will take a while, can we use your forked repo?

**Comment by rmillikin** [comment]
@rsdmse I think this should get merged quite soon, but if you want, you can pull the current smithchemwisc/metamorpheus:dev tag from dockerhub which includes this change. usually the dev tag is the current master branch, but I made an exception in this case and pushed this PR to the dev tag for testing in Singularity.

something like this (assuming you're using Singularity to pull from dockerhub):
singularity_mm

but in case that doesn't suit your purposes, yes you can definitely build this PR and use it as you wish.

**Comment by rmillikin** [comment]
@rsdmse it's not from my forked repo though, it's from a branch in this repo. https://github.com/smith-chem-wisc/MetaMorpheus/tree/optionalDataDir

**Comment by rsdmse** [comment]
Thanks so much for your prompt reply!

**Comment by trishorts** [comment]
I was unable to specify and output folder with quotations (either "" or '') which is need for file paths with spaces. 

e.g. "C:\User\Bob The Builder\Metamorpheus"

**Review by trishorts — APPROVED** [review]

**Comment by rmillikin** [comment]
@trishorts this might be a singularity issue but I can poke around for a solution.
https://github.com/hpcng/singularity/issues/5437
https://stackoverflow.com/questions/62963043/escaping-filename-spaces-with-singularity-files-directive

**Review by rmmiller22 — APPROVED** [review]

**Pull request merged**
