### PR TITLE
Restructure base directory

### PR DESCRIPTION
**Pull request by acesnik**
https://github.com/smith-chem-wisc/MetaMorpheus/issues/1956

### CODE REVIEW

**Comment by acesnik** [comment]
This PR aims to clean up the GitHub landing page by simplifying the base directory.

Before:
image

After:
image

**Comment by zrolfs** [comment]
NEAT!
Build failed, tho :(

**Comment by acesnik** [comment]
The AppVeyor, Jenkins, and Docker build scripts would need to be updated, since the MetaMorpheus.sln changed location. I guess I don't want to change that before we decide this is something we want to do.

**Review by zrolfs — APPROVED** [review]

**Review by trishorts — APPROVED** [review]
This is something I've wanted for a long time. Thanks Anthony.

**Comment by acesnik** [comment]
I think this may be something to do after changing over to Github Actions, since it will be straightforward to change the locations of the solution file and such within the workflow. https://github.com/smith-chem-wisc/MetaMorpheus/pull/2128

Going to take off the 'final review' label for now.

**Comment by acesnik** [comment]
Looking for a quick double-check that this is okay to merge, since the approval reviews are quite old. This is ready for merge after amending AppVeyor build and test scripts.

**Comment by acesnik** [comment]
## Concerns about `git blame` annotations
It sounds like the `git blame` annotations were messed up by the mzLib restructuring at some point, but from what I see in GitHub and Visual Studio 2022, that doesn't look to be the case anymore, and the blame looks informative:

### Visual Studio 2022
image (29)

### GitHub, Mar 2023
image (28)

**Comment by Alexander-Sol** [comment]
This restructure makes it very difficult to compare past commits to future commits. Git will list all pre-restructure files as "Deleted", and all post-restructure files as "Added." As such, direct comparison can't be done in Visual Studio. We ran into this issue with the mzLib restructure.

That being said, I think it's probably worth it to make the github page more user friendly.

**Comment by acesnik** [comment]
Cool, understood! Feel free to make a decision on your side and either merge or close this PR.

**Review by nbollis — APPROVED** [review]

**Review by Alexander-Sol — APPROVED** [review]

**Review by trishorts — APPROVED** [review]

**Pull request merged**
