### PR TITLE
Icon change

### PR DESCRIPTION
**Pull request by zrolfs**

### CODE REVIEW

**Comment by rmillikin** [comment]
the shade of purple seems a bit "off"/dull. can you use the same shade of purple that the current icon uses for the background?

**Comment by zrolfs** [comment]
image

**Comment by zrolfs** [comment]
Updated: 
image

**Comment by zrolfs** [comment]
I need the original vector; I'm losing pixels on each edit of the tiff @rmiller sent from her paper.

**Comment by zrolfs** [comment]
Okay, round 2. I intentionally went for a poppier color because I thought it looked better. Feel free to veto and I can revert. 
image

**Comment by zrolfs** [comment]
pointier corners, tried a sharpen tool for contrast 
image

**Comment by zrolfs** [comment]
I like the most recent one, if you guys are okay with that.

**Comment by zrolfs** [comment]
(I like Sean's more, for the record)

**Comment by acesnik** [comment]
Carrot with wings is all I can see now after Alexey made that comment

**Comment by acesnik** [comment]
🥕

**Pull request merged**
