### PR TITLE
Update to net5.0

### PR DESCRIPTION
**Pull request by acesnik**

### CODE REVIEW

**Comment by acesnik** [comment]
ready for review accompanying https://github.com/smith-chem-wisc/mzLib/pull/569

**Comment by acesnik** [comment]
Looks like this one will require some changes to the AppVeyor build. 😅

**Comment by acesnik** [comment]
@rmmiller22 @rmillikin @trishorts 

Hi there! This is a PR that's ready for review. It aims to update MM to net5.0, which is now the framework for mzLib. The motivation here was that net5.0 is now the default `dotnet` that is downloaded from `homebrew` and `conda` repositories, and there is also pretty substantial speed increases for certain computer architectures with the switch from `netcoreapp3.1` to `net5.0`.

This PR also fixes a few issues with the installer, such as creating the `Proteomes` folder with the installer in the target programs folder. Before, the file was being installed to the `Mods` folder, which made a crash when trying the new `Download Proteomes` feature with an installed version of MM.

There was also an issue with `mzPlot.dll` being installed in the `CMD` that led to a crash on linux. This is fixed because net5.0 and net5.0-windows are now explicit, so the files needed for WPF are now explicitly only downloaded for net5.0-windows and not net5.0 that is used for the `CMD` project.

Thanks! -AC

**Comment by acesnik** [comment]
NB: I changed `netcoreapp3.1` to `net5.0` in the AppVeyor environment variables `CommandLineBuildFolder` and `DotnetVersion` (a new variable, so that this is easier to reverse if needed) to get this PR to build.

**Review by zrolfs — APPROVED** [review]

**Review by rmillikin — APPROVED** [review]

**Comment by rmillikin** [comment]
looks good to me, probably worth double-checking to make sure the installer works. installed version ran ok on appveyor though.

**Comment by rmillikin** [comment]
I tested the installer on my machine (downloaded from appveyor via script) and the installer is 6x the size of the current installer (11 MB vs 65 MB) but it installs and MM runs ok

**Pull request merged**
