### PR TITLE
Pruned Db edits

### PR DESCRIPTION
**Pull request by rmmiller22**
1. fix bug Leah found that only proteins, who have peptide evidence have modification properly filtered prior to pruned database generation
2. old code cleared all original modifications for each protein and replaced with modifications for the database. this is problematic, especially since the peptide results are calculated after database generation. Code was added to store the original modifications and then reset to these after the databases are created.

### CODE REVIEW

**Comment by trishorts** [comment]
A unit test to hit these bulleted lines from the PostSearchAnalysisTask would be great. 
image

**Comment by lschaffer2** [comment]
Rachel would it be hard to add a unit test just like that one but make sure an artifact isn't added if it shouldn't be?

**Comment by rmmiller22** [comment]
Unit tests for the PostSearchAnalysisTask are pretty tricky but I will do my best to design ones to meet both of your requests

**Comment by rmmiller22** [comment]
> Rachel would it be hard to add a unit test just like that one but make sure an artifact isn't added if it shouldn't be?

Hi Leah, Upon re-familiarizing myself with my previous unit test. We already do check that artifacts are not being added to the database when we do not want them to be!

**Pull request merged**
